### ISSUE TITLE
npm start or npm run build gives error

### ISSUE THREAD

**Issue by summerice71** [onitsoft/nexchange-open-client-react#147]
hello
i get this error when trying to build or start npm from within the package directory
http://prntscr.com/hb2j7i
please let me know if any specific versions of node and npm need to be installed for getting it going..

ok,, the update is i updated node version to 6 and i now receive a new error upon running npm start.
http://prntscr.com/hb2nqg
please let me know how to proceed forward..

**Comment by punit2502** [comment]
did you run `npm install`?

**Comment by summerice71** [comment]
yes, i confirm "npm install" was run before using the "npm start"

**Comment by punit2502** [comment]
@summerice71 Can you delete the `node_modules` directory and run `npm install` again?

**Comment by summerice71** [comment]
ok, i have done that.. http://prntscr.com/hbiwhi
and then server seem to start but is again killed with the following message http://prntscr.com/hbiwn5
This is the log file generated.. 
[2017-11-17T04_40_13_994Z-debug.log](https://github.com/onitsoft/nexchange-open-client-react/files/1481052/2017-11-17T04_40_13_994Z-debug.log)

**Comment by punit2502** [comment]
@summerice71 not sure what the issue is. You are using Digitalocean?

**Comment by summerice71** [comment]
hello,
yes, i am using digital ocean server with the configuration 512 MB Memory / 20 GB Disk / NYC3 - Ubuntu 16.04.3 x64.

**Comment by punit2502** [comment]
@summerice71 can you try on a 1 or 2 GB RAM server?

**Comment by summerice71** [comment]
i have upgraded to 1GB RAM and deleted the node_modules folder and ran the "npm install" command. This is the output. http://prntscr.com/hbnqlj
Then ran the "npm start" command and server started running.. 
So if the minimum configuration requirements are updated in Readme.md file, it would be helpful for others.

**Comment by punit2502** [comment]
Tagging @BeOleg & @SarunasAzna
