### ISSUE TITLE
 Request header field x-referral-token is not allowed by Access-Control-Allow-Headers

### ISSUE THREAD

**Issue by jrischma** [onitsoft/nexchange-open-client-react#178]
Hi my friend, u work is amazing, really congratulations.

Look, i have a problem, server return this:

Failed to load https://api.myweb.com/en/api/v1/price/dogeltc/latest/: Request header field x-referral-token is not allowed by Access-Control-Allow-Headers in preflight response.
CoinPrices.js:89 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)
(index):1 Failed to load https://api.myweb.com/en/api/v1/price/btceth/latest/: Request header field x-referral-token is not allowed by Access-Control-Allow-Headers in preflight response.
PriceComparison.js:81 Error: Network Error
    at createError (createError.js:16)
    at XMLHttpRequest.handleError (xhr.js:87)
(index):1 Failed to load https://api.myweb.com/en/api/v1/price/ethltc/latest/: Request header field x-referral-token is not allowed by Access-Control-Allow-Headers in preflight response.
(index):1 Failed to load https://api.myweb.com/en/api/v1/price/dogebtc/latest/: Request header field x-referral-token is not allowed by Access-Control-Allow-Headers in preflight response.
(index):1 Failed to load https://api.myweb.com/en/api/v1/price/btcltc/latest/: Request header field x-referral-token is not allowed by Access-Control-Allow-Headers in preflight response.
(index):1 Failed to load https://api.myweb.com/en/api/v1/price/dogeeth/latest/: Request header field x-referral-token is not allowed by Access-Control-Allow-Headers in preflight response.
(index):1 Failed to load https://api.myweb.com/en/api/v1/price/dogeltc/latest/: Request header field x-referral-token is not allowed by Access-Control-Allow-Headers in preflight response.

and https://api.myweb.com/en/api/v1/ return 404 error

thanks for u help, regards

**Comment by BeOleg** [comment]
Hi there, thank you for the kind words, I think the problem is that you are not sending a cors header / cookie.
Could that be the case?
https://stackoverflow.com/questions/5750696/how-to-get-a-cross-origin-resource-sharing-cors-post-request-working
This answer has all variants however please refer to answer #4 by `Dekel` for the jQuery variant.

**Comment by superkarolis** [comment]
Based on the URL it seems like API is making an invalid request to `https://api.myweb.com`. From this I can make a conclusion that you changed `API_BASE_URL` field in `config.js` file. It should be left as `https://api.nexchange.io/en/api/v1`.
