### ISSUE TITLE
QR code on trade page not scan-able by blockchain.info wallet

### ISSUE THREAD

**Issue by BeOleg** [onitsoft/nexchange-open-client-react#184]
`Error: 1LXnNemLQxuXjGUpP3rh2TYX9NJ35i1yZk?amount=0.1 is not a valid BTC address`

Solution: remove amount from QR code / patch otherwise.

**Comment by BeOleg** [comment]
Test with blockchain info wallet and validate that the code is the same as the one that is displayed as a string.

**Comment by superkarolis** [comment]
Fixed
