### ISSUE TITLE
Error location is fixed and not visible when scrolling down

### ISSUE THREAD

**Issue by BeOleg** [onitsoft/nexchange-open-client-react#185]
Should be 'static 0 0'

**Comment by superkarolis** [comment]
Do you reckon it should be static all the way down? If the user scrolls down below the exchange widget area, maybe the error is not relevant anymore. Thus, perhaps it should only stay within the boundaries of an exchange widget, what do you think?

**Comment by BeOleg** [comment]
If the error appears it means the user interacted with the exchange widget.
That by it self is enough to keep the error fixed to the top.
