### ISSUE TITLE
Amounts should change respectively when pairs shift

### ISSUE THREAD

**Issue by BeOleg** [onitsoft/nexchange-open-client-react#186]
Default deposit amount should shift when user changes, for example deposited currency from XVG to BTC, not to get an error which says 'You cannot deposit 6000 BTC'

**Comment by superkarolis** [comment]
How should the default amount for each coin be calculated? Currently, the default amount is 10x the minimal deposit.

**Comment by BeOleg** [comment]
this is fine

**Comment by BeOleg** [comment]
It might also make sense to put `1` whenever one of the coins is `major` (LTC, BTC, ETH, BCH).
Either one is fine.
