### ISSUE TITLE
Etherscan can't find transaction

### ISSUE THREAD

**Issue by Aracher17** [onitsoft/nexchange-open-client-react#208]
Etherscan returns an "Invalid TxHash" for the transaction id (displayed: https://etherscan.io/tx/5758022d44791ad526c26cfc2519ded01862f38ba53a66b1f1ecacab9e9bfca2)
Order example: https://nexchange.io/order/OA5GFP

**Comment by superkarolis** [comment]
Could you specify in which order state you found this issue? I am unable to replicate the problem.

**Comment by Aracher17** [comment]
While waiting for the confirmations during the deposit transaction

**Comment by superkarolis** [comment]
I tried replicating this issue with several orders (https://nexchange.io/order/OSM67U and https://nexchange.io/order/O6QYZC) but all works fine. Closing this issue for now.
