### ISSUE TITLE
Fiat orders KYC verification screen won`t change if it fails.

### ISSUE THREAD

**Issue by murilob** [onitsoft/nexchange-open-client-react#211]
After sending fiat payment, it is shown to the user the "awaiting verification status screen" informing that If we do not get these documents within 2 hours, we will refund the order. If the costumer don`t send the documentation within the two hours window, then it should inform that the order has been refunded. Instead, order gets stuck in the "awaiting verification status" forever, even is the real status of the order  "12 - unconfirmed payment".

example: https://coinsready.io/order/OLGLHX

**Comment by superkarolis** [comment]
Hi there, investigating it now, good catch.

**Comment by BeOleg** [comment]
This is in fact a backend issue, we only refund by hand now, not by an automated timer.
This needs to be developed and thoroughly tested.
@SarunasAzna
