### ISSUE TITLE
do you support erc20 tokens

### ISSUE THREAD

**Issue by happyse27** [onitsoft/nexchange-open-client-react#218]
Hi Support,

 Do you support ERC 20 tokens?

Thanks

**Comment by BeOleg** [comment]
Hello @happyse27.

We do support ERC20 tokens.
Amongst them OMG, BDG, and many more to come.

Is there anything specific you are interested in?
Please write support@nexchange.io or contact us via the designated support form / live chat on nexchange.io

**Comment by happyse27** [comment]
Hi support, I am using a2 hosting. Can I install the environment(what technical and hosting requirement) to test the basic configuration? And to handle bigger loads of traffic 

Any legal issue I need to take note?


Thanks


do you support erc20 tokens #218
@happyse27
happyse27 opened this issue 
4 days ago 
Hi Support,

Do you support ERC 20 tokens?

Thanks
@BeOleg
BeOleg 
commented about 14 hours ago
Hello @happyse27.

We do support ERC20 tokens.
Amongst them OMG, BDG, and many more to come.

Is there anything specific you are interested in?
Please write support@nexchange.io or contact us via the designated support form / live chat on nexchange.io


--------------------------------------------
On Mon, 19/3/18, Oleg Belousov <notifications@github.com> wrote:

 Subject: Re: [onitsoft/nexchange-open-client-react] do you support erc20 tokens (#218)
 To: "onitsoft/nexchange-open-client-react" <nexchange-open-client-react@noreply.github.com>
 Cc: "happyse27" <happyse27@yahoo.com>, "Mention" <mention@noreply.github.com>
 Received: Monday, 19 March, 2018, 3:59 AM
 
 Closed #218.
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by happyse27** [comment]
Hello Andrew.
As far as I understand you want to add your own ERC20 token to the system.

This would not be possible by using our open-sourced frontend as it would
require us to make backend modifications.

It is possible to have a white-label with custom tokens, but it requires to
be a subscriber of our managed premium solution, and incurs some extra
costs for coin / token listing, whether it is privately only on your
white-label or over the whole eco-system.

Regards,
Nexchange Support.
On Mon, Mar 19, 2018 at 12:11 PM Andrew Se <happyse27@yahoo.com> wrote:

> Hi support, I am using a2 hosting. Can I install the environment(what
> technical and hosting requirement) to test the basic configuration? And to
> handle bigger loads of traffic
>
> Any legal issue I need to take note?
>
>
> Thanks
>
>
> do you support erc20 tokens #218
> @happyse27
> happyse27 opened this issue
> 4 days ago
> Hi Support,
>
> Do you support ERC 20 tokens?
>
> Thanks
> @BeOleg
> BeOleg
> commented about 14 hours ago
> Hello @happyse27.
>
> We do support ERC20 tokens.
> Amongst them OMG, BDG, and many more to come.
>
> Is there anything specific you are interested in?
> Please write support@nexchange.io or contact us via the designated
> support form / live chat on nexchange.io
>
>
> --------------------------------------------
> On Mon, 19/3/18, Oleg Belousov <notifications@github.com> wrote:
>
>  Subject: Re: [onitsoft/nexchange-open-client-react] do you support erc20
> tokens (#218)
>  To: "onitsoft/nexchange-open-client-react" <
> nexchange-open-client-react@noreply.github.com>
>  Cc: "happyse27" <happyse27@yahoo.com>, "Mention" <
> mention@noreply.github.com>
>  Received: Monday, 19 March, 2018, 3:59 AM
>
>  Closed #218.
>
>  —
>  You are receiving this because you were mentioned.
>  Reply to this email directly, view
>  it on GitHub, or mute
>  the thread.
>
>
>
>
>
>
>
>
>
> --






*.M#: +441412805847S#: +442081442192US#: +16464612858O.Book a Meeting
- calendly.com/beoleg <http://calendly.com/beoleg>*

**Comment by happyse27** [comment]
Hi, 

1)  What is the charges? 

 2) And I understand basic configuration can support eth/ ltc and btc right? 
 
 3) And existing erc 20 tokens is it need to customise also?

 4) what is the time frame to customise? 

 5) security how to handle?

Thanks 
--------------------------------------------
On Mon, 19/3/18, Nexchange Support <support@nexchange.io> wrote:

 Subject: Re: [onitsoft/nexchange-open-client-react] do you support erc20 tokens (#218)
 To: "Andrew Se" <happyse27@yahoo.com>
 Cc: "onitsoft/nexchange-open-client-react" <nexchange-open-client-react@noreply.github.com>, "onitsoft/nexchange-open-client-react" <reply@reply.github.com>, "Mention" <mention@noreply.github.com>, "Chirag Neb" <chirag@nexchange.co.uk>
 Received: Monday, 19 March, 2018, 6:16 PM
 
 
 Hello Andrew.As far as I understand you
 want to add your own ERC20 token to the
 system.
 This would not
 be possible by using our open-sourced frontend as it would
 require us to make backend modifications.
 It is possible to have a white-label
 with custom tokens, but it requires to be a subscriber of
 our managed premium solution, and incurs some extra costs
 for coin / token listing, whether it is privately only on
 your white-label or over the whole eco-system.
 Regards,Nexchange
 Support.On Mon, Mar
 19, 2018 at 12:11 PM Andrew Se <happyse27@yahoo.com>
 wrote:
 Hi
 support, I am using a2 hosting. Can I install the
 environment(what technical and hosting requirement) to test
 the basic configuration? And to handle bigger loads of
 traffic
 
 
 
 Any legal issue I need to take note?
 
 
 
 
 
 Thanks
 
 
 
 
 
 do you support erc20 tokens #218
 
 @happyse27
 
 happyse27 opened this issue
 
 4 days ago
 
 Hi Support,
 
 
 
 Do you support ERC 20 tokens?
 
 
 
 Thanks
 
 @BeOleg
 
 BeOleg
 
 commented about 14 hours ago
 
 Hello @happyse27.
 
 
 
 We do support ERC20 tokens.
 
 Amongst them OMG, BDG, and many more to come.
 
 
 
 Is there anything specific you are interested in?
 
 Please write support@nexchange.io
 or contact us via the designated support form / live chat on
 nexchange.io
 
 
 
 
 
 --------------------------------------------
 
 On Mon, 19/3/18, Oleg Belousov <notifications@github.com>
 wrote:
 
 
 
  Subject: Re: [onitsoft/nexchange-open-client-react] do you
 support erc20 tokens (#218)
 
  To: "onitsoft/nexchange-open-client-react"
 <nexchange-open-client-react@noreply.github.com>
 
  Cc: "happyse27" <happyse27@yahoo.com>,
 "Mention" <mention@noreply.github.com>
 
  Received: Monday, 19 March, 2018, 3:59 AM
 
 
 
  Closed #218.
 
 
 
  —
 
  You are receiving this because you were mentioned.
 
  Reply to this email directly, view
 
  it on GitHub, or mute
 
  the thread.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 -- 
 .
 M#:
 +441412805847
 S#: +442081442192
 US#: +16464612858
 O.
 
 Book a Meeting - calendly.com/beoleg

**Comment by happyse27** [comment]
Hi Support,

 6) I am using A2hosting.com, what is the server specification?


Thanks 

--------------------------------------------
On Mon, 19/3/18, Andrew Se <happyse27@yahoo.com> wrote:

 Subject: Re: [onitsoft/nexchange-open-client-react] do you support erc20 tokens (#218)
 To: "Andrew Se" <happyse27@yahoo.com>, "Nexchange Support" <support@nexchange.io>
 Cc: "onitsoft/nexchange-open-client-react" <nexchange-open-client-react@noreply.github.com>, "onitsoft/nexchange-open-client-react" <reply@reply.github.com>, "Mention" <mention@noreply.github.com>, "Chirag Neb" <chirag@nexchange.co.uk>
 Received: Monday, 19 March, 2018, 7:46 PM
 
 Hi, 
 
 1)  What is the charges? 
 
  2) And I understand basic
 configuration can support eth/ ltc and btc right? 
  
  3) And existing erc 20 tokens is it
 need to customise also?
 
  4) what is the time frame to
 customise? 
 
  5) security how to handle?
 
 Thanks 
 --------------------------------------------
 On Mon, 19/3/18, Nexchange Support
 <support@nexchange.io>
 wrote:
 
  Subject: Re:
 [onitsoft/nexchange-open-client-react] do you support erc20
 tokens (#218)
  To: "Andrew Se" <happyse27@yahoo.com>
  Cc:
 "onitsoft/nexchange-open-client-react" <nexchange-open-client-react@noreply.github.com>,
 "onitsoft/nexchange-open-client-react" <reply@reply.github.com>,
 "Mention" <mention@noreply.github.com>,
 "Chirag Neb" <chirag@nexchange.co.uk>
  Received: Monday, 19 March, 2018, 6:16
 PM
  
  
  Hello Andrew.As far as I understand
 you
  want to add your own ERC20 token to
 the
  system.
  This would not
  be possible by using our open-sourced
 frontend as it would
  require us to make backend
 modifications.
  It is possible to have a white-label
  with custom tokens, but it requires to
 be a subscriber of
  our managed premium solution, and
 incurs some extra costs
  for coin / token listing, whether it
 is privately only on
  your white-label or over the whole
 eco-system.
  Regards,Nexchange
  Support.On Mon, Mar
  19, 2018 at 12:11 PM Andrew Se <happyse27@yahoo.com>
  wrote:
  Hi
  support, I am using a2 hosting. Can I
 install the
  environment(what technical and hosting
 requirement) to test
  the basic configuration? And to handle
 bigger loads of
  traffic
  
  
  
  Any legal issue I need to take note?
  
  
  
  
  
  Thanks
  
  
  
  
  
  do you support erc20 tokens #218
  
  @happyse27
  
  happyse27 opened this issue
  
  4 days ago
  
  Hi Support,
  
  
  
  Do you support ERC 20 tokens?
  
  
  
  Thanks
  
  @BeOleg
  
  BeOleg
  
  commented about 14 hours ago
  
  Hello @happyse27.
  
  
  
  We do support ERC20 tokens.
  
  Amongst them OMG, BDG, and many more
 to come.
  
  
  
  Is there anything specific you are
 interested in?
  
  Please write support@nexchange.io
  or contact us via the designated
 support form / live chat on
  nexchange.io
  
  
  
  
  
 
 --------------------------------------------
  
  On Mon, 19/3/18, Oleg Belousov <notifications@github.com>
  wrote:
  
  
  
   Subject: Re:
 [onitsoft/nexchange-open-client-react] do you
  support erc20 tokens (#218)
  
   To:
 "onitsoft/nexchange-open-client-react"
  <nexchange-open-client-react@noreply.github.com>
  
   Cc: "happyse27" <happyse27@yahoo.com>,
  "Mention" <mention@noreply.github.com>
  
   Received: Monday, 19 March, 2018,
 3:59 AM
  
  
  
   Closed #218.
  
  
  
   —
  
   You are receiving this because you
 were mentioned.
  
   Reply to this email directly, view
  
   it on GitHub, or mute
  
   the thread.
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  -- 
  .
  M#:
  +441412805847
  S#: +442081442192
  US#: +16464612858
  O.
  
  Book a Meeting - calendly.com/beoleg

**Comment by punit2502** [comment]
Hi, Github issues is not the correct place for support. Please message us on [Slack](https://join.slack.com/t/nexchangecommunity/shared_invite/MjM0OTU1ODc4NTkyLTE1MDQ0Mzc3NjEtYzZiMTYxMjdhNA) or email us at support@nexchange.io

**Comment by happyse27** [comment]
--------------------------------------------
On Mon, 19/3/18, Andrew Se <happyse27@yahoo.com> wrote:

 Subject: Re: [onitsoft/nexchange-open-client-react] do you support erc20 tokens (#218)
 To: "Andrew Se" <happyse27@yahoo.com>, "Nexchange Support" <support@nexchange.io>
 Cc: "onitsoft/nexchange-open-client-react" <nexchange-open-client-react@noreply.github.com>, "onitsoft/nexchange-open-client-react" <reply@reply.github.com>, "Mention" <mention@noreply.github.com>, "Chirag Neb" <chirag@nexchange.co.uk>
 Received: Monday, 19 March, 2018, 7:53 PM
 
 Hi Support,
 
  6) I am using A2hosting.com, what is
 the server specification?
 
 
 Thanks 
 
 --------------------------------------------
 On Mon, 19/3/18, Andrew Se <happyse27@yahoo.com>
 wrote:
 
  Subject: Re:
 [onitsoft/nexchange-open-client-react] do you support erc20
 tokens (#218)
  To: "Andrew Se" <happyse27@yahoo.com>,
 "Nexchange Support" <support@nexchange.io>
  Cc:
 "onitsoft/nexchange-open-client-react" <nexchange-open-client-react@noreply.github.com>,
 "onitsoft/nexchange-open-client-react" <reply@reply.github.com>,
 "Mention" <mention@noreply.github.com>,
 "Chirag Neb" <chirag@nexchange.co.uk>
  Received: Monday, 19 March, 2018, 7:46
 PM
  
  Hi, 
  
  1)  What is the charges? 
  
   2) And I understand basic
  configuration can support eth/ ltc and
 btc right? 
   
   3) And existing erc 20 tokens is
 it
  need to customise also?
  
   4) what is the time frame to
  customise? 
  
   5) security how to handle?
  
  Thanks 
 
 --------------------------------------------
  On Mon, 19/3/18, Nexchange Support
  <support@nexchange.io>
  wrote:
  
   Subject: Re:
  [onitsoft/nexchange-open-client-react]
 do you support erc20
  tokens (#218)
   To: "Andrew Se" <happyse27@yahoo.com>
   Cc:
  "onitsoft/nexchange-open-client-react"
 <nexchange-open-client-react@noreply.github.com>,
  "onitsoft/nexchange-open-client-react"
 <reply@reply.github.com>,
  "Mention" <mention@noreply.github.com>,
  "Chirag Neb" <chirag@nexchange.co.uk>
   Received: Monday, 19 March,
 2018, 6:16
  PM
   
   
   Hello Andrew.As far as I
 understand
  you
   want to add your own ERC20 token
 to
  the
   system.
   This would not
   be possible by using our
 open-sourced
  frontend as it would
   require us to make backend
  modifications.
   It is possible to have a
 white-label
   with custom tokens, but it
 requires to
  be a subscriber of
   our managed premium solution,
 and
  incurs some extra costs
   for coin / token listing,
 whether it
  is privately only on
   your white-label or over the
 whole
  eco-system.
   Regards,Nexchange
   Support.On Mon, Mar
   19, 2018 at 12:11 PM Andrew Se
 <happyse27@yahoo.com>
   wrote:
   Hi
   support, I am using a2 hosting.
 Can I
  install the
   environment(what technical and
 hosting
  requirement) to test
   the basic configuration? And to
 handle
  bigger loads of
   traffic
   
   
   
   Any legal issue I need to take
 note?
   
   
   
   
   
   Thanks
   
   
   
   
   
   do you support erc20 tokens
 #218
   
   @happyse27
   
   happyse27 opened this issue
   
   4 days ago
   
   Hi Support,
   
   
   
   Do you support ERC 20 tokens?
   
   
   
   Thanks
   
   @BeOleg
   
   BeOleg
   
   commented about 14 hours ago
   
   Hello @happyse27.
   
   
   
   We do support ERC20 tokens.
   
   Amongst them OMG, BDG, and many
 more
  to come.
   
   
   
   Is there anything specific you
 are
  interested in?
   
   Please write support@nexchange.io
   or contact us via the
 designated
  support form / live chat on
   nexchange.io
   
   
   
   
   
  
 
 --------------------------------------------
   
   On Mon, 19/3/18, Oleg Belousov
 <notifications@github.com>
   wrote:
   
   
   
    Subject: Re:
  [onitsoft/nexchange-open-client-react]
 do you
   support erc20 tokens (#218)
   
    To:
 
 "onitsoft/nexchange-open-client-react"
   <nexchange-open-client-react@noreply.github.com>
   
    Cc: "happyse27" <happyse27@yahoo.com>,
   "Mention" <mention@noreply.github.com>
   
    Received: Monday, 19 March,
 2018,
  3:59 AM
   
   
   
    Closed #218.
   
   
   
    —
   
    You are receiving this because
 you
  were mentioned.
   
    Reply to this email directly,
 view
   
    it on GitHub, or mute
   
    the thread.
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   -- 
   .
   M#:
   +441412805847
   S#: +442081442192
   US#: +16464612858
   O.
   
   Book a Meeting
 - calendly.com/beoleg
