### ISSUE TITLE
Order quote amount unavailable to translate for localization

### ISSUE THREAD

**Issue by MKTHINGS** [onitsoft/nexchange-open-client-react#225]
Unable to find in code
![image](https://user-images.githubusercontent.com/27106794/37554655-4797f482-29dc-11e8-99f0-affd23f2bb66.png)

**Comment by MKTHINGS** [comment]
Same for **Maximal amount**
![image](https://user-images.githubusercontent.com/27106794/37554693-ab84ea04-29dc-11e8-89e2-e2865a544d54.png)

**Comment by MKTHINGS** [comment]
Same for **Base amount**
![image](https://user-images.githubusercontent.com/27106794/37554718-04edea5a-29dd-11e8-85f3-5c497db22523.png)

**Comment by BeOleg** [comment]
Hi @MKTHINGS the errors are generated by the backend.
We would be more than glad the expose to you the .po files if you would like to participate in the localisation for your native language :)

**Comment by MKTHINGS** [comment]
Hi @BeOleg, for sure, invite me to any your project also in the future, I am available to do that

**Comment by BeOleg** [comment]
Hi, let's continue the discussion on slack.
I am closing this issue.

https://join.slack.com/t/nexchangecommunity/shared_invite/enQtMjM0OTU1ODc4NTkyLTg0ZTFhNjY2NzM1OTFhMWYzNjUzZDQxZWNlZTc5NjE2OGUzNDZkZGZjNDFhMDlhMWM1YzliYmY3YTAxYzU2MGY
