### ISSUE TITLE
Module not found: Failed to compile.

### ISSUE THREAD

**Issue by Iridexx** [onitsoft/nexchange-open-client-react#348]
Hello, as soon as I start using the "npm start" command, the following error appears
![2018-08-11 22_39_02-miner rig1_](https://user-images.githubusercontent.com/36953698/43995858-5fca3566-9db7-11e8-8f66-e019f54eb37b.png)
is it possible to have help?

**Comment by BeOleg** [comment]
Seems like you have forgotten ‘npm install’

**Comment by Iridexx** [comment]
I ran npm install, but then I also used "npm audit fix" because errors were reported, now I re-run "npm install" started "npm start" and the result is this. 
![2018-08-12 09_47_51-miner rig1_](https://user-images.githubusercontent.com/36953698/43999842-f718f9c2-9e14-11e8-88cf-ea64351f025f.png)

I'm working in ssh can I access remotely?
Ty for you support.

**Comment by punit2502** [comment]
From your last screenshot, it compiled successfully with warnings.

If you are installing front-end client in your local machine then try to access `http://localhost:3000` in your browser and if in cloud then follow this guide: https://medium.com/nexchange/nexchange-io-front-end-client-setup-on-a-server-501ea46f34aa

**Comment by Iridexx** [comment]
ok thanks everyone very nice, is there any active exchange that used this platform?

**Comment by BeOleg** [comment]
Try https://coinwale.com

**Comment by BeOleg** [comment]
Closing issue.
Please let us know if you need further assistance.
