### ISSUE TITLE
npm start failing after successful cloning and installation of dependencies

### ISSUE THREAD

**Issue by abduladi** [onitsoft/nexchange-open-client-react#455]
**Describe the bug**

After cloning and installing dependencies, the frontend application fails to start when you run npm start.

**To Reproduce**

1. Make sure you have NPM and Node installed on your system.
2. type git clone https://github.com/onitsoft/nexchange-open-client-react.git.
3. cd nexchange-open-client-react.
4. npm install.
5. npm start.
6. you will get error

**Expected behavior**

**Screenshots**

This was done on a macbook PRO running macOS high sierra 10.13.1 node v10.15.3 and npm v6.4.1
<img width="973" alt="Screen Shot 2019-04-18 at 1 02 43 PM" src="https://user-images.githubusercontent.com/5064447/56359938-dd97f900-61da-11e9-92c4-7e4753a2bec1.png">

**Comment by MMrj9** [comment]
Hi @abduladi 

I solved this issue by upgrading webpack from 3 to 4, and also upgrading webpack related packages.
https://github.com/MMrj9/nexchange-open-client-react/blob/adjust/update-npm-packages/package.json

**Comment by abduladi** [comment]
I copied the contents of your package.json and replaced with mine. I did an npm install again, then npm start. still not working

**Comment by MMrj9** [comment]
Same error? 
If its the same error try deleting node modules and then running npm install
If its something like "this.htmlWebpackPlugin.getHooks is not a function", it's because these new package version have some breaking changes and required some tweaks. Maybe your best option is to clone the staging branch

**Comment by BeOleg** [comment]
Hi there @abduladi!
We have recently fixed this issue by upgrading webpack to version `4` #436

**Comment by abduladi** [comment]
After installing webpack, I get those dependency issues.

<img width="963" alt="Screen Shot 2019-04-18 at 5 33 56 PM" src="https://user-images.githubusercontent.com/5064447/56376598-3463f980-6200-11e9-93e4-c389c4bc62aa.png">

**Comment by MMrj9** [comment]
Copy the package.json as you did before and copy the webpack configuration files /config/webpack.config.dev.js and /config/webpack.config.prod.js from the staging branch

**Comment by abduladi** [comment]
> Same error?
> If its the same error try deleting node modules and then running npm install
> If its something like "this.htmlWebpackPlugin.getHooks is not a function", it's because these new package versions have some breaking changes and required some configuration tweaks. Maybe your best option is to clone the staging branch

Thanks! I cloned the staging branch. no hiccups. I will suggest updating the master branch to reflect this stability.
